const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8',...extra}});
const now=()=>new Date().toISOString();
const uid=()=>crypto.randomUUID();
async function sha256(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function b64(bytes){let s='';bytes.forEach(x=>s+=String.fromCharCode(x));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function unb64(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const bin=atob(s);return Uint8Array.from(bin,c=>c.charCodeAt(0))}
async function passwordHash(password,salt=b64(crypto.getRandomValues(new Uint8Array(16)))){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:unb64(salt),iterations:120000,hash:'SHA-256'},key,256);return `${salt}.${b64(new Uint8Array(bits))}`}
async function verifyPassword(password,stored){const [salt,val]=stored.split('.');const h=await passwordHash(password,salt);return h===stored}
function cookie(token){return `kkp_session=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000`}
function clearCookie(){return 'kkp_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0'}
async function currentUser(req,env){const m=req.headers.get('cookie')||'';const token=(m.match(/(?:^|; )kkp_session=([^;]+)/)||[])[1];if(!token)return null;const th=await sha256(token);const r=await env.DB.prepare('SELECT u.id,u.email,u.name,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?').bind(th,Date.now()).first();return r||null}
function admin(u){return u?.role==='admin'}
function text(v){return String(v??'').trim()}
function autoTitle(c){return text(c).split(/\n+/).find(Boolean)?.slice(0,100)||'नई कहानी'}
function autoExcerpt(c){const t=text(c).replace(/\s+/g,' ');return t.slice(0,180)+(t.length>180?'…':'')}
const emojis={'भूत':'👻','प्रेम':'❤️','प्रेरणादायक':'💡','भगवान':'🙏','भक्ति':'🙏','परिवार':'👨‍👩‍👧','रहस्यमयी':'🕵️','जानवरों की कहानी':'🐯','बच्चों की कहानी':'🧒','News':'📰','Blog':'📝'};
async function upload(req,env,u){if(!admin(u))return json({error:'Admin login required'},403);const form=await req.formData();const file=form.get('file');if(!(file instanceof File))return json({error:'File missing'},400);if(file.size>100*1024*1024)return json({error:'File too large (max 100 MB)'},413);const type=file.type.startsWith('video/')?'video':'image';if(type==='image'&&!file.type.startsWith('image/'))return json({error:'Image required'},400);const key=`${type}/${uid()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;await env.MEDIA.put(key,file.stream(),{httpMetadata:{contentType:file.type}});return json({url:`/api/media/${encodeURIComponent(key)}`,key,type})}

async function seedIfEmpty(env){
  const c=await env.DB.prepare('SELECT COUNT(*) n FROM stories').first();
  if(Number(c?.n||0)>0) return;
  const rows=[
   ['seed-1','ईश्वर पर भरोसा','भगवान','🙏','एक गरीब किसान ने कठिन समय में भी भगवान पर भरोसा नहीं छोड़ा।','एक गाँव में रामू नाम का किसान रहता था। एक साल बारिश नहीं हुई। खेत सूख गए, लेकिन रामू ने मेहनत और विश्वास नहीं छोड़ा। उसने रोज खेत में पानी बचाने के छोटे-छोटे उपाय किए। कुछ दिनों बाद अचानक अच्छी बारिश हुई और उसकी फसल बच गई। गाँव वालों ने उसकी मेहनत देखकर सीखा कि विश्वास के साथ कर्म करना भी जरूरी है।','सिर्फ भरोसा नहीं, सही कर्म भी जरूरी है।'],
   ['seed-2','पुरानी हवेली का रहस्य','रहस्यमयी','🏚️','एक सुनसान हवेली में हर रात सुनाई देने वाली आवाज का सच क्या था?','गाँव के बाहर एक पुरानी हवेली थी। लोग कहते थे कि रात में वहाँ किसी के चलने की आवाज आती है। एक रात मोहन ने हिम्मत करके अंदर जाने का फैसला किया। उसने देखा कि टूटी खिड़की से हवा आती और लकड़ी का पुराना दरवाजा अपने आप हिलता था। रहस्य का सच सामने आते ही सबकी डर की कहानी खत्म हो गई।','हर डर के पीछे हमेशा कोई रहस्य या कारण हो सकता है।'],
   ['seed-3','सच्चा दोस्त','प्रेरणादायक','💡','मुसीबत में साथ देने वाला ही सच्चा दोस्त होता है।','अमन और रोहन बचपन के दोस्त थे। परीक्षा के समय अमन बीमार पड़ गया। रोहन ने अपनी पढ़ाई के साथ उसे नोट्स दिए और पढ़ाया। परीक्षा में दोनों अच्छे अंक लाए। अमन समझ गया कि दोस्ती केवल खुशी बाँटने का नाम नहीं, बल्कि कठिन समय में साथ देने का नाम है।','सच्चा दोस्त वही है जो मुश्किल समय में साथ दे।'],
   ['seed-4','चतुर खरगोश','जानवरों की कहानी','🐇','एक छोटे खरगोश ने अपनी बुद्धि से जंगल को बचाया।','जंगल में एक शेर रोज जानवरों को परेशान करता था। एक दिन खरगोश ने शेर को कुएँ के पास ले जाकर पानी में उसकी परछाईं दिखाई। शेर ने उसे दूसरा शेर समझकर कुएँ में छलांग लगा दी। जंगल के जानवर सुरक्षित हो गए।','बुद्धि ताकत से बड़ी हो सकती है।'],
   ['seed-5','माँ की सीख','परिवार','👨‍👩‍👧','एक बेटे को माँ की छोटी सी सीख जीवनभर याद रही।','सोनू हमेशा जल्दी में काम करता था। उसकी माँ कहती थी कि हर काम सोच-समझकर करना चाहिए। एक दिन उसने बिना जाँच किए जरूरी कागज फाड़ दिया और परेशानी में पड़ गया। तब उसे माँ की बात याद आई। उसने गलती सुधारी और आगे से धैर्य रखना सीख लिया।','बड़ों की अच्छी सीख समय पर बहुत काम आती है।'],
   ['seed-6','बारिश वाली रात','भूत','👻','एक डरावनी रात में बच्चे को मिला एक अनोखा सच।','तेज बारिश वाली रात में दीपक ने अपने कमरे के बाहर किसी के रोने की आवाज सुनी। वह डरते हुए बाहर गया तो उसे पड़ोसी की बूढ़ी दादी मिलीं, जो रास्ता भटक गई थीं। दीपक उन्हें घर तक ले गया। सुबह पूरे गाँव ने उसकी बहादुरी की तारीफ की।','साहस का मतलब डर न होना नहीं, बल्कि डर के बावजूद सही काम करना है।']
  ];
  for(const r of rows) await env.DB.prepare('INSERT OR IGNORE INTO stories(id,title,category,emoji,excerpt,content,lesson) VALUES(?,?,?,?,?,?,?)').bind(...r).run();
}
export async function onRequest(context){const {request,env}=context;const url=new URL(request.url);const path=url.pathname.replace(/^\/api\/?/,'');
try{
 if(path.startsWith('media/')){const key=decodeURIComponent(path.slice(6));const o=await env.MEDIA.get(key);if(!o)return new Response('Not found',{status:404});return new Response(o.body,{headers:{'content-type':o.httpMetadata?.contentType||'application/octet-stream','cache-control':'public,max-age=31536000,immutable'}})}
 if(request.method==='GET'&&path==='health')return json({ok:true,cloudflare:true});
 if(path==='auth/signup'&&request.method==='POST'){const b=await request.json();const email=text(b.email).toLowerCase(),password=String(b.password||''),name=text(b.name);if(!email||password.length<6)return json({error:'Email और कम से कम 6 अक्षर का password जरूरी है'},400);const exists=await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first();if(exists)return json({error:'यह email पहले से registered है'},409);const count=await env.DB.prepare('SELECT COUNT(*) n FROM users').first();const admins=await env.DB.prepare("SELECT COUNT(*) n FROM users WHERE role='admin'").first();const role=(Number(count.n||0)===0||Number(admins.n||0)===0||(env.BOOTSTRAP_ADMIN_EMAIL&&email===env.BOOTSTRAP_ADMIN_EMAIL.toLowerCase()))?'admin':'user';const id=uid(),ph=await passwordHash(password);await env.DB.prepare('INSERT INTO users(id,email,password_hash,name,role) VALUES(?,?,?,?,?)').bind(id,email,ph,name,role).run();return await doLogin(id,email,env)}
 if(path==='auth/login'&&request.method==='POST'){const b=await request.json();const email=text(b.email).toLowerCase(),password=String(b.password||'');const u=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind(email).first();if(!u||!(await verifyPassword(password,u.password_hash)))return json({error:'Email या password गलत है'},401);return await doLogin(u.id,u.email,env)}
 if(path==='auth/logout'&&request.method==='POST'){const m=request.headers.get('cookie')||'',token=(m.match(/(?:^|; )kkp_session=([^;]+)/)||[])[1];if(token)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha256(token)).run();return json({ok:true},200,{'set-cookie':clearCookie()})}
 if(path==='auth/me'&&request.method==='GET'){const u=await currentUser(request,env);return json({user:u})}
 if(path==='stories'&&request.method==='GET'){await seedIfEmpty(env);const q=text(url.searchParams.get('q')).toLowerCase();let sql='SELECT * FROM stories ORDER BY created_at DESC';let r=await env.DB.prepare(sql).all();let rows=r.results||[];if(q)rows=rows.filter(x=>JSON.stringify(x).toLowerCase().includes(q)||x.title.toLowerCase().includes(q));return json({items:rows})}
 if(path==='story'&&request.method==='GET'){const id=text(url.searchParams.get('id'));const r=await env.DB.prepare('SELECT * FROM stories WHERE id=?').bind(id).first();if(!r)return json({error:'कहानी नहीं मिली'},404);await env.DB.prepare('UPDATE stories SET views=views+1 WHERE id=?').bind(id).run();r.views=(r.views||0)+1;return json({item:r})}
 if(path==='posts'&&request.method==='GET'){const type=text(url.searchParams.get('type'));if(!['news','blog'].includes(type))return json({error:'Invalid type'},400);const r=await env.DB.prepare('SELECT * FROM posts WHERE type=? AND status="published" ORDER BY COALESCE(published_at,created_at) DESC').bind(type).all();return json({items:r.results||[]})}
 if(path==='post'&&request.method==='GET'){const id=text(url.searchParams.get('id'));const r=await env.DB.prepare('SELECT * FROM posts WHERE id=? AND status="published"').bind(id).first();return r?json({item:r}):json({error:'Post नहीं मिला'},404)}
 if(path==='submit'&&request.method==='POST'){const b=await request.json(),u=await currentUser(request,env);const content=text(b.content);if(!content)return json({error:'कहानी जरूरी है'},400);const title=text(b.title)||autoTitle(content),category=text(b.category)||'कहानी';await env.DB.prepare('INSERT INTO submissions(id,user_id,author_name,title,category,excerpt,content,lesson,image_url,video_url,status) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(uid(),u?.id||null,text(b.author_name)||u?.name||'Anonymous',title,category,text(b.excerpt)||autoExcerpt(content),content,text(b.lesson),text(b.image_url),text(b.video_url),'pending').run();return json({ok:true})}
 if(path==='chat'&&request.method==='GET'){const u=await currentUser(request,env);if(!u)return json({error:'Login required'},401);const r=await env.DB.prepare('SELECT c.id,c.message,c.created_at,u.name,u.email FROM chat_messages c JOIN users u ON u.id=c.user_id WHERE c.room_id="public" ORDER BY c.created_at ASC LIMIT 300').all();return json({items:r.results||[]})}
 if(path==='chat'&&request.method==='POST'){const u=await currentUser(request,env);if(!u)return json({error:'Login required'},401);const b=await request.json(),m=text(b.message);if(!m)return json({error:'Message खाली है'},400);await env.DB.prepare('INSERT INTO chat_messages(id,room_id,user_id,message) VALUES(?,?,?,?)').bind(uid(),'public',u.id,m.slice(0,1000)).run();return json({ok:true})}
 if(path==='analytics'&&request.method==='POST'){const b=await request.json();await env.DB.prepare('INSERT INTO page_views(path,story_id) VALUES(?,?)').bind(text(b.path).slice(0,300),text(b.story_id)||null).run();return json({ok:true})}
 if(path==='analytics'&&request.method==='GET'){const u=await currentUser(request,env);if(!admin(u))return json({error:'Admin required'},403);const total=await env.DB.prepare('SELECT COUNT(*) n FROM page_views').first();const today=await env.DB.prepare("SELECT COUNT(*) n FROM page_views WHERE date(created_at)=date('now')").first();const stories=await env.DB.prepare('SELECT COALESCE(SUM(views),0) n FROM stories').first();return json({pageViews:Number(total.n||0),today:Number(today.n||0),storyViews:Number(stories.n||0)})}
 if(path==='admin/stories'&&request.method==='GET'){await seedIfEmpty(env);const u=await currentUser(request,env);if(!admin(u))return json({error:'Admin required'},403);const r=await env.DB.prepare('SELECT * FROM stories ORDER BY created_at DESC').all();return json({items:r.results||[]})}
 if(path==='admin/story'&&request.method==='POST'){const u=await currentUser(request,env);if(!admin(u))return json({error:'Admin required'},403);const b=await request.json(),content=text(b.content);if(!content)return json({error:'कहानी जरूरी है'},400);const id=text(b.id)||uid(),title=text(b.title)||autoTitle(content),category=text(b.category)||'भगवान';const row=[title,category,text(b.emoji)||emojis[category]||'📖',text(b.excerpt)||autoExcerpt(content),content,text(b.lesson),text(b.image_url),text(b.video_url)];if(b.id)await env.DB.prepare('UPDATE stories SET title=?,category=?,emoji=?,excerpt=?,content=?,lesson=?,image_url=?,video_url=?,updated_at=? WHERE id=?').bind(...row,now(),id).run();else await env.DB.prepare('INSERT INTO stories(id,title,category,emoji,excerpt,content,lesson,image_url,video_url) VALUES(?,?,?,?,?,?,?,?,?)').bind(id,...row).run();return json({ok:true,id})}
 if(path==='admin/story'&&request.method==='DELETE'){const u=await currentUser(request,env);if(!admin(u))return json({error:'Admin required'},403);const id=text(url.searchParams.get('id'));await env.DB.prepare('DELETE FROM stories WHERE id=?').bind(id).run();return json({ok:true})}
 if(path==='admin/posts'&&request.method==='GET'){const u=await currentUser(request,env);if(!admin(u))return json({error:'Admin required'},403);const r=await env.DB.prepare('SELECT * FROM posts ORDER BY created_at DESC').all();return json({items:r.results||[]})}
 if(path==='admin/post'&&request.method==='POST'){const u=await currentUser(request,env);if(!admin(u))return json({error:'Admin required'},403);const b=await request.json(),type=text(b.type);if(!['news','blog'].includes(type))return json({error:'Type invalid'},400);const id=text(b.id)||uid(),title=text(b.title),content=text(b.content);if(!title||!content)return json({error:'Title और content जरूरी हैं'},400);const vals=[type,title,text(b.category),text(b.excerpt)||autoExcerpt(content),content,text(b.image_url),text(b.status)||'published',(text(b.status)||'published')==='published'?now():null];if(b.id)await env.DB.prepare('UPDATE posts SET type=?,title=?,category=?,excerpt=?,content=?,image_url=?,status=?,published_at=?,updated_at=? WHERE id=?').bind(...vals,now(),id).run();else await env.DB.prepare('INSERT INTO posts(id,type,title,category,excerpt,content,image_url,status,published_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(id,...vals).run();return json({ok:true,id})}
 if(path==='admin/post'&&request.method==='DELETE'){const u=await currentUser(request,env);if(!admin(u))return json({error:'Admin required'},403);await env.DB.prepare('DELETE FROM posts WHERE id=?').bind(text(url.searchParams.get('id'))).run();return json({ok:true})}
 if(path==='admin/submissions'&&request.method==='GET'){const u=await currentUser(request,env);if(!admin(u))return json({error:'Admin required'},403);const r=await env.DB.prepare('SELECT * FROM submissions ORDER BY created_at DESC').all();return json({items:r.results||[]})}
 if(path==='admin/submission'&&request.method==='POST'){const u=await currentUser(request,env);if(!admin(u))return json({error:'Admin required'},403);const b=await request.json(),id=text(b.id),status=text(b.status);const s=await env.DB.prepare('SELECT * FROM submissions WHERE id=?').bind(id).first();if(!s)return json({error:'Submission not found'},404);if(status==='approved'){const storyId=uid();await env.DB.prepare('INSERT INTO stories(id,title,category,emoji,excerpt,content,lesson,image_url,video_url) VALUES(?,?,?,?,?,?,?,?,?)').bind(storyId,s.title,s.category,emojis[s.category]||'📖',s.excerpt,s.content,s.lesson,s.image_url,s.video_url).run()}await env.DB.prepare('UPDATE submissions SET status=? WHERE id=?').bind(status,id).run();return json({ok:true})}
 if(path==='admin/upload'&&request.method==='POST')return upload(request,env,await currentUser(request,env));
 if(path==='migrate'&&request.method==='POST'){const u=await currentUser(request,env);if(!admin(u))return json({error:'Admin required'},403);const b=await request.json();if(!Array.isArray(b.stories)&&!Array.isArray(b.posts))return json({error:'No data'},400);for(const s of (b.stories||[])){await env.DB.prepare('INSERT OR IGNORE INTO stories(id,title,category,emoji,excerpt,content,lesson,image_url,video_url,views,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(String(s.id),s.title||autoTitle(s.content||''),s.category||'कहानी',s.emoji||emojis[s.category]||'📖',s.excerpt||autoExcerpt(s.content||''),s.content||'',s.lesson||'',s.image_url||'',s.video_url||'',Number(s.views||0),s.created_at||now()).run()}for(const p of (b.posts||[])){await env.DB.prepare('INSERT OR IGNORE INTO posts(id,type,title,category,excerpt,content,image_url,status,published_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(String(p.id),p.type,p.title,p.category||'',p.excerpt||'',p.content||'',p.image_url||'',p.status||'published',p.published_at||now(),p.created_at||now()).run()}return json({ok:true})}
 return json({error:'Not found'},404)
}catch(e){return json({error:e?.message||String(e)},500)}
}
async function doLogin(id,email,env){const token=uid()+uid(),th=await sha256(token);await env.DB.prepare('INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,?)').bind(th,id,Date.now()+2592000000).run();const u=await env.DB.prepare('SELECT id,email,name,role FROM users WHERE id=?').bind(id).first();return json({user:u},200,{'set-cookie':cookie(token)})}
