name = "kahanikapitara"
compatibility_date = "2026-08-20"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "kahanikapitara-db"
database_id = "38238d09-90de-40b3-813f-28bff8850ce4"
[vars]
BOOTSTRAP_ADMIN_EMAIL = "Jivaibhav650@gmail.com"
